# VERSÃO DO NODE
FROM node:16
# ONDE SERÁ PUBLICADO DENTRO DO DOCKERFILE DIRETORIO RAIZ DO PROJETO
WORKDIR /usr/src/clea-node-api
# COPIANDO O PACKAGE JOSN PARA A RAIZ DO DOCKER
COPY ./package.json .
# RODAR O COMANDO PARA INSTALAR AS DEPENDENCIAS que serão utilizadas em produção apenas
RUN npm install --only=prod
# COPiAR A pASTA DIST QUE É A APLICAÇÂO COMPILADA E PRONTA PARA PUBLICAÇÃO
COPY ./dist ./dist
# ABRIR UM PORTA PARA APLICAÇÃO FICAR EXPOSTA
EXPOSE 5000
# RODAR UM COMANDO PARA STARTAR A APLICAÇÃO
CMD npm start
